/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joerg' at '11.03.15 13:26' with Gradle 2.1
 *
 * @author joerg, @date 11.03.15 13:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
